version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # ブラウザで見る用の画面
      - "7687:7687" # Goプログラムから接続する用のポート
    environment:
      - NEO4J_AUTH=neo4j/password # ユーザー名/パスワード
    volumes:
      - ./neo4j_data:/data # データを保存する場所